"""Run the bounded ``structnpe`` 0.1.0b1 beta-evidence replication stages."""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any, Callable

from helpers import (
    CONFIGS,
    EXPECTED,
    ROOT,
    compare_expected,
    git_metadata,
    load_json,
    machine_metadata,
    replication_environment,
    repository_relative,
    run_command,
    sha256_file,
    utc_now,
    validate_replication_configs,
    write_json,
)


STAGE_ORDER = (
    "package_tests",
    "build_distributions",
    "wheel_install",
    "sdist_install",
    "conjugate_normal",
    "sbc_32",
    "structural_grid",
    "support_warning",
    "save_reload",
    "cpu_neural",
    "benchmark",
)

STAGE_DESCRIPTIONS = {
    "package_tests": "Run the complete package test suite.",
    "build_distributions": "Build the wheel and source distribution.",
    "wheel_install": "Install and import the built wheel in a temporary environment.",
    "sdist_install": "Build-install and import the source distribution in a temporary environment.",
    "conjugate_normal": "Run the predeclared conjugate-normal exact-posterior smoke profile.",
    "sbc_32": "Audit the 32-case SBC diagnostics generated by the conjugate smoke run.",
    "structural_grid": "Run the twelve-check structural exact-grid smoke profile.",
    "support_warning": "Trigger the fixed training-support diagnostic using a synthetic shifted observation.",
    "save_reload": "Check fixed-seed draws after save/reload in a fresh Python process.",
    "cpu_neural": "Fit and infer with a deliberately tiny CPU neural demonstration.",
    "benchmark": "Repeat the frozen component benchmark; timing remains non-gating.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=("smoke", "full"), default="smoke")
    parser.add_argument(
        "--only",
        help="Comma-separated stage IDs to run. Omit to select every smoke stage.",
    )
    parser.add_argument(
        "--skip",
        default="",
        help="Comma-separated selected stage IDs to mark SKIPPED.",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("replication/results/smoke"),
        help="Generated artifacts and logs (relative paths resolve from repository root).",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=None,
        help="Machine-readable report path; defaults to RESULTS_DIR/report.json.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate configs and write a PLANNED report without running subprocesses.",
    )
    parser.add_argument(
        "--use-recorded-evidence",
        action="store_true",
        help="Allow comparison-only stages to use committed 0.1.0b1 output when fresh output is absent.",
    )
    return parser.parse_args()


def _csv(value: str | None) -> set[str]:
    if not value:
        return set()
    return {item.strip() for item in value.split(",") if item.strip()}


def _resolve(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def _command_stage(
    *,
    name: str,
    command: list[str],
    display: list[str],
    results_dir: Path,
    timeout: int,
    extra_environment: dict[str, str] | None = None,
) -> dict[str, Any]:
    environment = replication_environment()
    environment.update(extra_environment or {})
    return run_command(
        name=name,
        command=command,
        display_command=display,
        log_dir=results_dir / "logs",
        timeout_seconds=timeout,
        environment=environment,
    )


def _artifact_details(paths: list[Path]) -> list[dict[str, Any]]:
    return [
        {
            "path": repository_relative(path),
            "bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        }
        for path in paths
        if path.is_file()
    ]


def _find_distribution(results_dir: Path, kind: str) -> Path:
    distribution = results_dir / "distributions"
    pattern = "structnpe-0.1.0b1-*.whl" if kind == "wheel" else "structnpe-0.1.0b1.tar.gz"
    candidates = sorted(distribution.glob(pattern))
    if not candidates:
        raise FileNotFoundError(
            f"No {kind} found under {repository_relative(distribution)}; run build_distributions first."
        )
    return candidates[-1]


def _run_package_tests(results_dir: Path, pipeline: dict[str, Any]) -> dict[str, Any]:
    timeout = pipeline["stages"]["package_tests"]["timeout_seconds"]
    return _command_stage(
        name="package_tests",
        command=[sys.executable, "-m", "pytest", "-q"],
        display=["python", "-m", "pytest", "-q"],
        results_dir=results_dir,
        timeout=timeout,
    )


def _run_build(results_dir: Path, pipeline: dict[str, Any]) -> dict[str, Any]:
    output = results_dir / "distributions"
    output.mkdir(parents=True, exist_ok=True)
    timeout = pipeline["stages"]["build_distributions"]["timeout_seconds"]
    result = _command_stage(
        name="build_distributions",
        command=[sys.executable, "-m", "build", "--outdir", str(output)],
        display=["python", "-m", "build", "--outdir", repository_relative(output)],
        results_dir=results_dir,
        timeout=timeout,
    )
    if result["status"] == "PASS":
        artifacts = sorted(output.glob("structnpe-0.1.0b1*"))
        if not any(path.suffix == ".whl" for path in artifacts) or not any(path.name.endswith(".tar.gz") for path in artifacts):
            result["status"] = "FAIL"
            result["error"] = "Build returned success without both 0.1.0b1 distribution formats."
        else:
            sdist = next(path for path in artifacts if path.name.endswith(".tar.gz"))
            normalization = _command_stage(
                name="normalize_sdist",
                command=[
                    sys.executable,
                    str(ROOT / "scripts" / "normalize_sdist.py"),
                    str(sdist),
                ],
                display=[
                    "python",
                    "scripts/normalize_sdist.py",
                    repository_relative(sdist),
                ],
                results_dir=results_dir,
                timeout=60,
            )
            result["sdist_normalization"] = normalization
            if normalization["status"] != "PASS":
                result["status"] = "FAIL"
                result["error"] = "Public sdist metadata normalization failed."
            else:
                distribution_audit = _command_stage(
                    name="distribution_boundary",
                    command=[
                        sys.executable,
                        "-m",
                        "pytest",
                        "-q",
                        str(ROOT / "tests" / "test_structnpe_distribution_contents.py"),
                    ],
                    display=[
                        "python",
                        "-m",
                        "pytest",
                        "-q",
                        "tests/test_structnpe_distribution_contents.py",
                    ],
                    results_dir=results_dir,
                    timeout=120,
                    extra_environment={"STRUCTNPE_DIST_DIR": str(output)},
                )
                result["distribution_boundary"] = distribution_audit
                if distribution_audit["status"] != "PASS":
                    result["status"] = "FAIL"
                    result["error"] = "Built distribution boundary audit failed."
        result["artifacts"] = _artifact_details(artifacts)
    return result


def _run_install(results_dir: Path, pipeline: dict[str, Any], kind: str) -> dict[str, Any]:
    stage = f"{kind}_install"
    artifact = _find_distribution(results_dir, kind)
    output = results_dir / "install_checks" / f"{stage}.json"
    timeout = pipeline["stages"][stage]["timeout_seconds"]
    result = _command_stage(
        name=stage,
        command=[
            sys.executable,
            str(ROOT / "replication" / "scripts" / "install_check.py"),
            "--artifact",
            str(artifact),
            "--kind",
            kind,
            "--output",
            str(output),
        ],
        display=[
            "python",
            "replication/scripts/install_check.py",
            "--artifact",
            repository_relative(artifact),
            "--kind",
            kind,
            "--output",
            repository_relative(output),
        ],
        results_dir=results_dir,
        timeout=timeout,
    )
    if output.is_file():
        result["result"] = repository_relative(output)
    return result


def _run_conjugate(results_dir: Path, config: dict[str, Any]) -> dict[str, Any]:
    output = results_dir / "conjugate_normal"
    result = _command_stage(
        name="conjugate_normal",
        command=[
            sys.executable,
            str(ROOT / "validation" / "exact_example" / "run_validation.py"),
            "--profile",
            "smoke",
            "--output-dir",
            str(output),
            "--quiet",
        ],
        display=[
            "python",
            "validation/exact_example/run_validation.py",
            "--profile",
            "smoke",
            "--output-dir",
            repository_relative(output),
            "--quiet",
        ],
        results_dir=results_dir,
        timeout=config["timeout_seconds"],
    )
    metrics = output / "validation_metrics.json"
    if metrics.is_file():
        result["metrics"] = repository_relative(metrics)
        result["metrics_sha256"] = sha256_file(metrics)
    return result


def _conjugate_evidence_path(results_dir: Path, allow_recorded: bool) -> tuple[Path, str]:
    fresh = results_dir / "conjugate_normal" / "validation_metrics.json"
    if fresh.is_file():
        return fresh, "fresh replication run"
    if allow_recorded:
        recorded = ROOT / "validation" / "exact_example" / "output" / "validation_metrics.json"
        if recorded.is_file():
            return recorded, "committed release evidence"
    raise FileNotFoundError("No conjugate validation metrics are available for the SBC stage.")


def _run_sbc(results_dir: Path, config: dict[str, Any], allow_recorded: bool) -> dict[str, Any]:
    started_at = utc_now()
    started = time.perf_counter()
    path, origin = _conjugate_evidence_path(results_dir, allow_recorded)
    payload = load_json(path)
    sbc = payload["sbc"]
    configuration = sbc["configuration"]
    regions = sbc["by_parameter_and_region"]
    histogram = sbc["rank_histogram"]
    conditions = [
        configuration["cases"] == config["cases"],
        configuration["posterior_draws_per_case"] == config["posterior_draws_per_case"],
        configuration["rank_histogram_bins"] == config["rank_histogram_bins"],
        [row["region"] for row in regions] == config["regions"],
        sum(histogram["counts"]) == config["cases"],
        config["acceptance"]["gating"] is False,
    ]
    if not all(conditions):
        raise RuntimeError("SBC output does not match the frozen 32-case descriptive configuration.")
    all_region = regions[0]
    return {
        "name": "sbc_32",
        "status": "PASS",
        "started_at": started_at,
        "finished_at": utc_now(),
        "duration_seconds": time.perf_counter() - started,
        "command": None,
        "evidence": repository_relative(path),
        "evidence_origin": origin,
        "gating": False,
        "interpretation": config["acceptance"]["reason"],
        "summary": {
            key: all_region[key]
            for key in ("n", "bias", "rmse", "coverage_50", "coverage_80", "coverage_90", "coverage_95", "mean_rank_fraction")
        },
    }


def _run_structural(results_dir: Path, config: dict[str, Any]) -> dict[str, Any]:
    output = results_dir / "structural_grid"
    result = _command_stage(
        name="structural_grid",
        command=[
            sys.executable,
            str(ROOT / "validation" / "structural_example" / "run_validation.py"),
            "--profile",
            "smoke",
            "--output-dir",
            str(output),
            "--quiet",
        ],
        display=[
            "python",
            "validation/structural_example/run_validation.py",
            "--profile",
            "smoke",
            "--output-dir",
            repository_relative(output),
            "--quiet",
        ],
        results_dir=results_dir,
        timeout=config["timeout_seconds"],
    )
    metrics = output / "validation_metrics.json"
    if metrics.is_file():
        result["metrics"] = repository_relative(metrics)
        result["metrics_sha256"] = sha256_file(metrics)
        payload = load_json(metrics)
        result["declared_checks"] = len(payload.get("checks", {}))
    return result


def _run_support(results_dir: Path, pipeline: dict[str, Any]) -> dict[str, Any]:
    config = pipeline["stages"]["support_warning"]
    output = results_dir / "support_warning" / "result.json"
    return _command_stage(
        name="support_warning",
        command=[
            sys.executable,
            str(ROOT / "replication" / "scripts" / "support_warning.py"),
            "--artifact",
            str(ROOT / "examples" / "assets" / "demo_estimator"),
            "--output",
            str(output),
            "--scale",
            str(config["observation_scale"]),
            "--draws",
            str(config["posterior_draws"]),
            "--seed",
            str(config["seed"]),
        ],
        display=[
            "python",
            "replication/scripts/support_warning.py",
            "--artifact",
            "examples/assets/demo_estimator",
            "--output",
            repository_relative(output),
            "--scale",
            str(config["observation_scale"]),
            "--draws",
            str(config["posterior_draws"]),
            "--seed",
            str(config["seed"]),
        ],
        results_dir=results_dir,
        timeout=config["timeout_seconds"],
    )


def _run_save_reload(results_dir: Path, pipeline: dict[str, Any]) -> dict[str, Any]:
    config = pipeline["stages"]["save_reload"]
    work = results_dir / "save_reload"
    return _command_stage(
        name="save_reload",
        command=[
            sys.executable,
            str(ROOT / "examples" / "save_reload.py"),
            "--work-dir",
            str(work),
            "--simulations",
            str(config["simulations"]),
            "--epochs",
            str(config["epochs"]),
            "--draws",
            str(config["posterior_draws"]),
            "--seed",
            str(config["seed"]),
            "--quiet",
        ],
        display=[
            "python",
            "examples/save_reload.py",
            "--work-dir",
            repository_relative(work),
            "--simulations",
            str(config["simulations"]),
            "--epochs",
            str(config["epochs"]),
            "--draws",
            str(config["posterior_draws"]),
            "--seed",
            str(config["seed"]),
            "--quiet",
        ],
        results_dir=results_dir,
        timeout=config["timeout_seconds"],
    )


def _run_cpu_neural(results_dir: Path, pipeline: dict[str, Any]) -> dict[str, Any]:
    config = pipeline["stages"]["cpu_neural"]
    output = results_dir / "cpu_neural" / "estimator"
    return _command_stage(
        name="cpu_neural",
        command=[
            sys.executable,
            str(ROOT / "examples" / "exact_toy.py"),
            "--simulations",
            str(config["simulations"]),
            "--epochs",
            str(config["epochs"]),
            "--draws",
            str(config["posterior_draws"]),
            "--seed",
            str(config["seed"]),
            "--output-dir",
            str(output),
            "--quiet",
        ],
        display=[
            "python",
            "examples/exact_toy.py",
            "--simulations",
            str(config["simulations"]),
            "--epochs",
            str(config["epochs"]),
            "--draws",
            str(config["posterior_draws"]),
            "--seed",
            str(config["seed"]),
            "--output-dir",
            repository_relative(output),
            "--quiet",
        ],
        results_dir=results_dir,
        timeout=config["timeout_seconds"],
    )


def _run_benchmark(results_dir: Path, config: dict[str, Any]) -> dict[str, Any]:
    values = config["configuration"]
    output = results_dir / "benchmark" / "benchmark_results.json"
    result = _command_stage(
        name="benchmark",
        command=[
            sys.executable,
            str(ROOT / "benchmarks" / "benchmark_inference.py"),
            "--simulations",
            str(values["simulations"]),
            "--epochs",
            str(values["epochs"]),
            "--draws",
            str(values["posterior_draws"]),
            "--batch-size",
            str(values["batch_size"]),
            "--repeats",
            str(values["repeats"]),
            "--seed",
            str(values["seed"]),
            "--output",
            str(output),
            "--quiet",
        ],
        display=[
            "python",
            "benchmarks/benchmark_inference.py",
            "--simulations",
            str(values["simulations"]),
            "--epochs",
            str(values["epochs"]),
            "--draws",
            str(values["posterior_draws"]),
            "--batch-size",
            str(values["batch_size"]),
            "--repeats",
            str(values["repeats"]),
            "--seed",
            str(values["seed"]),
            "--output",
            repository_relative(output),
            "--quiet",
        ],
        results_dir=results_dir,
        timeout=config["timeout_seconds"],
    )
    if output.is_file():
        result["metrics"] = repository_relative(output)
        result["metrics_sha256"] = sha256_file(output)
        result["timing_is_gating"] = False
    return result


def _planned_stage(name: str) -> dict[str, Any]:
    return {
        "name": name,
        "status": "PLANNED",
        "description": STAGE_DESCRIPTIONS[name],
        "command": "See the frozen JSON config and run_all.py stage definition.",
    }


def _failed_stage(name: str, error: Exception) -> dict[str, Any]:
    return {
        "name": name,
        "status": "FAIL",
        "started_at": utc_now(),
        "finished_at": utc_now(),
        "duration_seconds": 0.0,
        "error": f"{type(error).__name__}: {error}",
    }


def _load_evidence(results_dir: Path, allow_recorded: bool) -> dict[str, dict[str, Any]]:
    evidence: dict[str, dict[str, Any]] = {}
    candidates = {
        "conjugate_normal": results_dir / "conjugate_normal" / "validation_metrics.json",
        "structural_grid": results_dir / "structural_grid" / "validation_metrics.json",
        "benchmark": results_dir / "benchmark" / "benchmark_results.json",
    }
    recorded = {
        "conjugate_normal": ROOT / "validation" / "exact_example" / "output" / "validation_metrics.json",
        "structural_grid": ROOT / "validation" / "structural_example" / "output" / "validation_metrics.json",
        "benchmark": ROOT / "benchmarks" / "benchmark_results.json",
    }
    for name, path in candidates.items():
        if path.is_file():
            evidence[name] = load_json(path)
        elif allow_recorded and recorded[name].is_file():
            evidence[name] = load_json(recorded[name])
    return evidence


def _summary_status(stages: list[dict[str, Any]], comparisons: list[dict[str, Any]], dry_run: bool) -> str:
    if dry_run:
        return "PLANNED"
    if any(stage["status"] in {"FAIL", "BLOCKED"} for stage in stages):
        return "FAIL"
    if any(item["gating"] and item["passed"] is False for item in comparisons):
        return "FAIL"
    return "PASS"


def main() -> int:
    args = parse_args()
    config_audit = validate_replication_configs()
    results_dir = _resolve(args.results_dir)
    report_path = _resolve(args.report) if args.report is not None else results_dir / "report.json"
    selected = _csv(args.only) if args.only else set(STAGE_ORDER)
    skipped = _csv(args.skip)
    unknown = (selected | skipped) - set(STAGE_ORDER)
    if unknown:
        raise ValueError(f"Unknown stage ID(s): {', '.join(sorted(unknown))}")
    skipped &= selected
    active = selected - skipped
    started_at = utc_now()

    pipeline = load_json(CONFIGS / "pipeline_smoke.json")
    exact = load_json(CONFIGS / "conjugate_normal_smoke.json")
    sbc = load_json(CONFIGS / "sbc_32.json")
    structural = load_json(CONFIGS / "structural_grid_smoke.json")
    benchmark = load_json(CONFIGS / "cpu_benchmark.json")
    expected = load_json(EXPECTED)

    base_report: dict[str, Any] = {
        "schema_version": 1,
        "release": "0.1.0b1",
        "profile": args.profile,
        "started_at": started_at,
        "config_audit": config_audit,
        "selection": {
            "selected": [name for name in STAGE_ORDER if name in selected],
            "skipped": [name for name in STAGE_ORDER if name in skipped],
            "use_recorded_evidence": bool(args.use_recorded_evidence),
        },
        "machine": machine_metadata(),
        "version_control": git_metadata(),
        "stages": [],
        "comparisons": [],
    }

    if args.profile == "full":
        full = load_json(CONFIGS / "full_profile.json")
        stages = []
        for name in STAGE_ORDER:
            status = "SKIPPED" if name in skipped else ("UNRUN_FUTURE_WORK" if name in selected else "NOT_SELECTED")
            stages.append(
                {
                    "name": name,
                    "status": status,
                    "description": STAGE_DESCRIPTIONS[name],
                    "reason": full["execution_policy"] if status == "UNRUN_FUTURE_WORK" else None,
                }
            )
        report = {
            **base_report,
            "status": "UNRUN_FUTURE_WORK",
            "finished_at": utc_now(),
            "full_profile": full,
            "stages": stages,
            "summary": {
                "claim": "No full-profile result is claimed for 0.1.0b1.",
                "selected_unrun": sum(stage["status"] == "UNRUN_FUTURE_WORK" for stage in stages),
            },
        }
        write_json(report_path, report)
        print(json.dumps({"status": "UNRUN_FUTURE_WORK", "report": repository_relative(report_path)}, indent=2))
        return 0

    if args.dry_run:
        stages = []
        for name in STAGE_ORDER:
            if name in skipped:
                stages.append({"name": name, "status": "SKIPPED", "description": STAGE_DESCRIPTIONS[name]})
            elif name in selected:
                stages.append(_planned_stage(name))
            else:
                stages.append({"name": name, "status": "NOT_SELECTED", "description": STAGE_DESCRIPTIONS[name]})
        report = {
            **base_report,
            "status": "PLANNED",
            "finished_at": utc_now(),
            "stages": stages,
            "summary": {"planned": sum(stage["status"] == "PLANNED" for stage in stages)},
        }
        write_json(report_path, report)
        print(json.dumps({"status": "PLANNED", "report": repository_relative(report_path)}, indent=2))
        return 0

    runners: dict[str, Callable[[], dict[str, Any]]] = {
        "package_tests": lambda: _run_package_tests(results_dir, pipeline),
        "build_distributions": lambda: _run_build(results_dir, pipeline),
        "wheel_install": lambda: _run_install(results_dir, pipeline, "wheel"),
        "sdist_install": lambda: _run_install(results_dir, pipeline, "sdist"),
        "conjugate_normal": lambda: _run_conjugate(results_dir, exact),
        "sbc_32": lambda: _run_sbc(results_dir, sbc, args.use_recorded_evidence),
        "structural_grid": lambda: _run_structural(results_dir, structural),
        "support_warning": lambda: _run_support(results_dir, pipeline),
        "save_reload": lambda: _run_save_reload(results_dir, pipeline),
        "cpu_neural": lambda: _run_cpu_neural(results_dir, pipeline),
        "benchmark": lambda: _run_benchmark(results_dir, benchmark),
    }

    stages: list[dict[str, Any]] = []
    for name in STAGE_ORDER:
        if name not in selected:
            stages.append({"name": name, "status": "NOT_SELECTED", "description": STAGE_DESCRIPTIONS[name]})
            continue
        if name in skipped:
            stages.append({"name": name, "status": "SKIPPED", "description": STAGE_DESCRIPTIONS[name]})
            continue
        try:
            result = runners[name]()
        except Exception as error:  # retain a complete multi-stage report
            result = _failed_stage(name, error)
        result.setdefault("description", STAGE_DESCRIPTIONS[name])
        stages.append(result)
        partial = {**base_report, "status": "RUNNING", "stages": stages, "finished_at": None}
        write_json(report_path, partial)

    evidence = _load_evidence(results_dir, args.use_recorded_evidence)
    comparisons = compare_expected(expected, evidence, active)
    status = _summary_status(stages, comparisons, dry_run=False)
    counts = {state: sum(stage["status"] == state for stage in stages) for state in ("PASS", "FAIL", "SKIPPED", "NOT_SELECTED")}
    report = {
        **base_report,
        "status": status,
        "finished_at": utc_now(),
        "stages": stages,
        "comparisons": comparisons,
        "summary": {
            "stage_counts": counts,
            "gating_comparisons_passed": sum(item["gating"] and item["passed"] is True for item in comparisons),
            "gating_comparisons_failed": sum(item["gating"] and item["passed"] is False for item in comparisons),
            "descriptive_comparisons": sum(not item["gating"] for item in comparisons),
            "timing_is_gating": False,
            "scientific_scope": "Release-pipeline evidence only; no claim of general structural accuracy, identification, or specification validity.",
        },
    }
    write_json(report_path, report)
    print(json.dumps({"status": status, "report": repository_relative(report_path)}, indent=2))
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
